version: '3.3'
services:
  db:
    restart: always
    image: postgres:10
    volumes:
      - dbdatavol:/var/lib/postgresql/data

  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always
    env_file:
      - web-variables.env
    command: apache

  rssd:
    build: ./app
    depends_on:
      - db
      - app
    restart: always
    env_file:
      - web-variables.env
    command: update-daemon

volumes:
  dbdatavol:
    driver: local

